<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit57f30ad2b736a197024716135266156e
{
    public static $prefixLengthsPsr4 = array (
        'W' => 
        array (
            'Workerman\\' => 10,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Workerman\\' => 
        array (
            0 => __DIR__ . '/..' . '/workerman/workerman',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit57f30ad2b736a197024716135266156e::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit57f30ad2b736a197024716135266156e::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit57f30ad2b736a197024716135266156e::$classMap;

        }, null, ClassLoader::class);
    }
}
